- hosts: 192.168.1.200
  become: true
  tasks:

  - name: Create new VM with minimal options
    community.general.proxmox_kvm:
      proxmox_default_behavior: 'no_defaults'
      api_user: 'root@pam'
      api_password: 'AcDc1204@'
      api_host: '192.168.1.200'
      name: 'VM-via-Ansible'
      node: 'unzy'
